version: "3"

networks:
  news.net:
    driver: bridge

services:
  api.news:
    build: .
    networks:
      - news.net
    ports:
      - "5000:80"
    links:
      - mongo.cat:newsdb

  mongo.cat:
    image: mongo:latest
    working_dir: /var/data
    networks:
      - news.net
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    networks:
    - news.net
    ports:
    - "3000:8081"
    links:
    - mongo.cat:mongo
    
